services:
  db:
    image: postgres:16-alpine
    restart: always
    container_name: toolbox_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: toolbox_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d toolbox_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
